#!/usr/bin/ruby

require 'pathname'
script_dir = File.dirname(Pathname.new(__FILE__).realpath)
project_dir = Dir::getwd()

require 'optparse'
require 'yaml'
require 'rubygems'
Dir::chdir(script_dir)
require 'bundler/setup'
require 'aws-sdk'
require_relative 'lib/templatelib'
require_relative 'lib/cfglib'
Dir::chdir(project_dir)

cfgfile = "cloudconfig.yaml"
outputdir = "output"
upload = true
disable_rollback = false

opts = OptionParser.new

opts.banner = <<-EOF
Usage: cfn <command> (options) <templatename|templatedir> - manage a CloudFormation stack
 Where <command> is one of:
  generate - generate json templates for the stack
  list - list all stacks for the account
  create - create a new stack
  delete - delete a stack (warning: without confirmation, no resources retained)
  update - update a stack
  validate - run templates through validation
 <templatename> corresponds to a directory under cfn/, or you can specify the full path
 Options are:
EOF
opts.on("-t", "--jsondir DIRECTORY", "Use <templatedir>/DIRECTORY instead of <templatedir>/output for JSON files") do |dir|
	outputdir = dir
end
opts.on("-c", "--configfile FILE", "Use FILE for cloud configuration instead of ./cloudconfig.yaml") do |file|
	cfgfile = file
end
opts.on("-d", "--disable-rollback", "Disable rollback when a create or update fails") do |disable|
	disable_rollback = true
end

class UsageException < Exception
	def initialize(msg="Invalid command / option / argument")
		super(msg)
	end
end

begin

commands = [ "create", "delete", "generate", "list", "update", "validate" ]
command = ARGV.shift()
raise UsageException.new("Missing <command>") unless command
raise UsageException.new("Unknown command: #{command}") unless commands.include?(command)

opts.parse!

raise UsageException.new("Missing configuration file: #{cfgfile}") unless File::exist?(cfgfile)
raise UsageException.new("Not a regular file: #{cfgfile}") unless File::stat(cfgfile).file?

cfg = ConfigFile.new(cfgfile)

class Aws::CloudFormation::Client
	def validate(template, verbose=true)
		resp = validate_template({ template_body: template })
		if verbose
			puts "Description: #{resp.description}"
			if resp.capabilities.length > 0
				puts "Capabilities: #{resp.capabilities.join(",")}"
				puts "Reason: #{resp.capabilities_reason}"
			end
			puts
		end
		return resp.capabilities
	end
end

cfn = Aws::CloudFormation::Client.new( region: cfg["Region"] )
cnfres = Aws::CloudFormation::Resource.new( client: cfn )

s3 = Aws::S3::Resource.new( region: cfg["Region"] )

case command
when "list"
	stacklist = []
	stack_states = [ "CREATE_IN_PROGRESS", "CREATE_FAILED", "CREATE_COMPLETE", "ROLLBACK_IN_PROGRESS", "ROLLBACK_FAILED", "ROLLBACK_COMPLETE", "DELETE_IN_PROGRESS", "DELETE_FAILED", "UPDATE_IN_PROGRESS", "UPDATE_COMPLETE_CLEANUP_IN_PROGRESS", "UPDATE_COMPLETE", "UPDATE_ROLLBACK_IN_PROGRESS", "UPDATE_ROLLBACK_FAILED", "UPDATE_ROLLBACK_COMPLETE_CLEANUP_IN_PROGRESS", "UPDATE_ROLLBACK_COMPLETE" ]
	response = cfn.list_stacks({ stack_status_filter: stack_states })
	while true
		response.stack_summaries.each() do |stack|
			stacklist.push("#{stack.stack_name}: #{stack.stack_status}")
		end
		next_token = response.next_token
		break unless next_token
		response = cfn.list_stacks({
			stack_staus_filter: stack_states,
			next_token: next_token,
		})
	end
	if stacklist.length() > 0
		puts "Stacks:"
		puts stacklist
	else
		puts "No stacks found"
	end
	exit 0
end

template_arg = ARGV.shift()
raise UsageException.new("Missing <templatename|templatedir>") unless template_arg

template_arg = template_arg.chomp("/")
if template_arg.include?("/")
	templatename = File::basename(template_arg)
	templatedir = template_arg
else
	templatename = template_arg
	templatedir = "cfn/#{templatename}"
end

raise UsageException.new("Directory not found: #{templatedir}") unless File::exist?(templatedir)
raise UsageException.new("Not a directory: #{templatedir}") unless File::stat(templatedir).directory?

outputdir = templatedir + "/" + outputdir

if File::exist?(outputdir)
	raise UsageException.new("Not a directory: #{outputdir}") unless File::stat(outputdir).directory?
else
	if command == "generate"
		Dir::mkdir(outputdir)
	else
		raise UsageException.new("No such file or directory: #{outputdir}")
	end
end

# Generate the hub template that owns other templates
maincfg = MainTemplate.new(templatedir, templatename, cfg)
maincfg.process()
puts # blank line after 'Loading ...'

filenames = [ "main" ] + maincfg.children.map { |child| child.name().downcase() }
upload = false if filenames.length() == 1

stackprefix = (cfg["StackPrefix"]?cfg["StackPrefix"]:"")
stackname = stackprefix + templatename
stack_required_capabilities = []

case command
when "generate"
	maincfg.process_children()
	maincfg.write_all(outputdir)
when "create", "update", "validate"
	filenames.each() do |tfile|
		json = File::read(outputdir + "/" + tfile + ".json")
		case command
		when "validate"
			puts "Validating #{tfile}"
			cfn.validate(json)
		when "create", "update"
			required_capabilities = cfn.validate(json, false)
			if ! upload
				json = File::read(outputdir + "/" + tfile + ".json")
				params = {
					stack_name: stackname,
					tags: cfg["tags"],
					capabilities: required_capabilities,
					disable_rollback: disable_rollback,
					template_body: json,
				}
				if command == "create"
					puts "Creating #{stackname}"
					stackout = cfn.create_stack(params)
				else
					puts "Updating #{stackname}"
					params.delete(:disable_rollback)
					stackout = cfn.update_stack(params)
				end
				puts "Stack ID: #{stackout.stack_id}"
			else
				obj = s3.bucket(cfg["Bucket"]).object("#{cfg["Prefix"]}/#{templatename}/#{tfile}.json")
				puts "Uploading #{tfile}"
				obj.upload_file("#{outputdir}/#{tfile}.json")
				stack_required_capabilities = (stack_required_capabilities + required_capabilities).uniq()
			end
		end
	end
	if upload && [ "create", "update" ].include?(command)
		json = File::read(outputdir + "/main.json")
		template_url = "https://s3.amazonaws.com/#{cfg["Bucket"]}/#{cfg["Prefix"]}/#{templatename}/main.json"
		params = {
			stack_name: stackname,
			tags: cfg["tags"],
			capabilities: stack_required_capabilities,
			disable_rollback: disable_rollback,
			template_url: template_url,
		}
		if command == "create"
			puts "Creating #{stackname} from #{template_url}"
			stackout = cfn.create_stack(params)
		else
			puts "Updating #{stackname}"
			params.delete(:disable_rollback)
			stackout = cfn.update_stack(params)
		end
		puts "Stack ID: #{stackout.stack_id}"
	end
when "delete"
	puts "Deleting #{stackname}"
	cfn.delete_stack({ stack_name: stackname })
end

rescue UsageException => e
	puts "\n#{e.message}\n\n"
	puts opts.help()
end
