---
AWSTemplateFormatVersion: '2010-09-09'
Description: Private DNS Zone for VPCs, to integrate with ruby-awstools DNS updates

Parameters:
  ZoneName:
    Description: The private DNS zone to create
    Type: String

Resources:

  PrivateDNS:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref ZoneName
      VPCs:
      # NOTE: The private DNS resource will need to be updated for each client
      # VPC added.
      # - VPCId: ${=MgmtVPC:rVPCManagement}
      #   VPCRegion: us-east-1
      # - VPCId: ${=ProdVPC:rVPCProduction}
      #   VPCRegion: us-east-1
      # - VPCId: ${=DevelVPC:rVPCProduction}
      #   VPCRegion: us-east-1
